name: Debug build

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type"
        required: false
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Release
      branchName:
        description: "Branch name"
        required: false
        default: 'development'
      buildBrand:
        description: "Brand"
        required: false
        default: 'plusTv'


  pull_request_target:
    types:
      - closed
    branches:
      - 'ci_test'
      - 'development'

env:
  BUILD_TYPE: ${{inputs.buildType}}


jobs:

  build:
    # Start workflow only if it was run manually using 'workflow_dispatch' or pull request was merged
    if: ${{ github.event.pull_request.merged || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to branch
      if: inputs.branchName != ${{ github.ref_name }}
      uses: actions/checkout@v3
      with:
        ref: ${{inputs.branchName}}

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean build
      run: ./gradlew clean

    - name: Set build information
      run: |
         echo "VERSION_INFO=$(${{github.workspace}}/gradlew -q printVersionInformation)" >> $GITHUB_ENV
         echo "BUILD_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Show  path and file
      run: |
        echo "${{ inputs.buildBrand }}-${{ inputs.buildType }}-${{ env.VERSION_INFO }}-${{ env.BUILD_DATE }}"
        echo "${{ env.MAIN_PROJECT_MODULE }}/build/outputs/${{ inputs.buildType }}/**/"
        
    - name: Build with Gradle
      run: ./gradlew assemble${{ inputs.buildType }}
       

#    - name: Build with Gradle
#      run: |
#        if [$BUILD_TYPE == 'debug']; then
#          ./gradlew assembleDebug
#        else
#          ./gradlew assembleRelease
#        fi
#
#    - name: Upload APK
#      uses: actions/upload-artifact@v2
#      with:
#        name: ${{ inputs.buildBrand }}-${{ inputs.buildType }}-${{ env.VERSION_INFO }}-${{ env.BUILD_DATE }}
#        path: ${{ env.MAIN_PROJECT_MODULE }}/build/outputs/${{ inputs.buildType }}/**/
