name: Debug build

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type"
        required: false
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      branchName:
        description: "Branch name"
        required: false
        default: 'development'


jobs:
  build:
    runs-on: ubuntu-latest


    env:
      BUILD_TYPE: ${{inputs.buildType}}
      APK_NAME_DEBUG: 'app-debug.apk'
      APK_NAME_RELEASE: 'app-release.apk'
      APK_FILE_PATH_DEBUG: 'app/build/outputs/apk/debug/app-debug.apk'
      APK_FILE_PATH_RELEASE: 'app/build/outputs/apk/release/app-debug.apk'


      APK_NAME_VALUE: ""
      APK_FILE_PATH: ""


    steps:
    - name: Checkout to branch
      if: inputs.branchName != ${{ github.ref_name }}
      uses: actions/checkout@v3
      with:
        ref: ${{inputs.branchName}}

    - name: Setup outputs
      run: |
        if [$BUILD_TYPE == 'debug']; than
          APK_NAME_VALUE=$APK_NAME_DEBUG
        else
          APK_NAME_VALUE=$APK_NAME_RELEASE
        fi
        
        if [$BUILD_TYPE == 'debug']; than
          APK_FILE_PATH=$APK_FILE_PATH_DEBUG
        else
          APK_FILE_PATH=$APK_FILE_PATH_RELEASE
        fi
    

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        if [[$BUILD_TYPE == 'debug']]; than
          ./gradlew assembleDebug
        else
          ./gradlew assembleRelease
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: $APK_NAME
        path: $APK_FILE_PATH
